#!/bin/sh
cd "$(dirname "$0")"

cd Assets
cd Emgu.TF.Lite
mkdir -p Assets
cd Assets
mkdir -p Scripts
cd Scripts

rm -rf Emgu.LiteRT.Util
mkdir -p Emgu.LiteRT.Util
rm -rf Emgu.TF.Lite
mkdir -p Emgu.TF.Lite
rm -rf Emgu.Models
mkdir -p Emgu.Models
rm -rf Emgu.TF.Lite.Models
mkdir -p Emgu.TF.Lite.Models

cd ..
cd ..
cd ..
cd ..

cp ../tensorflow/LICENSE Assets/Emgu.TF.Lite/Documentation/tensorflow.license.txt
#cp unityStoreIcons/README.txt Assets/Emgu.TF/README.txt

cp ../Emgu.LiteRT.Util/*.cs Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.LiteRT.Util/
cp ../Emgu.LiteRT.Tflite/*.cs Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.TF.Lite/
cp ../Emgu.Models/*.cs Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.Models/
cp ../Emgu.LiteRT.Tflite.Models/*.cs Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.TF.Lite.Models/

cd Assets/Emgu.TF.Lite/Plugins
if test -d "../../../../platforms/macos/tfliteextern.bundle"
then
    cp -rf ../../../../platforms/macos/tfliteextern.bundle ./
fi
