#!/bin/sh
cd "$(dirname "$0")"

cp Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.LiteRT.Util/*.cs ../Emgu.LiteRT.Util/
cp Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.TF.Lite/*.cs ../Emgu.LiteRT.Tflite/
cp Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.Models/*.cs ../Emgu.Models/
cp Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.TF.Lite.Models/*.cs ../Emgu.LiteRT.Tflite.Models/